services:
  db:
    image: postgres:alpine
    ports:
    - 30001:5432
    environment:
    - POSTGRES_USER=auth-test
    - POSTGRES_PASSWORD=testing123
    volumes:
    - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
    driver: local
   